### PR TITLE
[#93766344] Adds EditorConfig file which should be supported by all editor around

### PR DESCRIPTION
**Pull request by Kuranes**
http://editorconfig.org/ for editor plugin list to install

### CODE REVIEW

**Comment by Kuranes** [comment]
Notes: 
- disabled for js until grunt lintspaces fixed https://github.com/schorfES/grunt-lintspaces/issues/21 (better we make a PR on their github so that it's fixed faster)
- Didn't add it to check as there is currently glsl error . Do I fix them in this PR ?
```
unning "lintspaces:external" (lintspaces) task
☓ examples/earlyz/fragment.glsl
  L55: Expected an indentation at 24 instead of at 23.
☓ sources/osgShader/node/functions.glsl
  L98: Expected an indentation at 6 instead of at 5.
☓ sources/osgShader/node/lights.glsl
  L45: Expected an indentation at 30 instead of at 29.
  L46: Expected an indentation at 30 instead of at 29.
  L48: Expected an indentation at 30 instead of at 29.
  L49: Expected an indentation at 30 instead of at 29.
  L50: Expected an indentation at 30 instead of at 29.
  L51: Expected an indentation at 30 instead of at 29.
  L53: Expected an indentation at 30 instead of at 29.
  L54: Expected an indentation at 30 instead of at 29.
  L55: Expected an indentation at 30 instead of at 29.
  L57: Expected an indentation at 30 instead of at 29.
  L58: Expected an indentation at 30 instead of at 29.
  L59: Expected an indentation at 30 instead of at 29.
  L60: Expected an indentation at 30 instead of at 29.
  L61: Expected an indentation at 30 instead of at 29.
  L63: Expected an indentation at 30 instead of at 29.
  L64: Expected an indentation at 30 instead of at 29.
  L66: Expected an indentation at 30 instead of at 29.
  L67: Expected an indentation at 30 instead of at 29.
  L68: Expected an indentation at 30 instead of at 29.
  L69: Expected an indentation at 30 instead of at 29.
```

**Comment by cedricpinson** [comment]
if it fails just disable grunt check

**Comment by cedricpinson** [comment]
is it still useful if we use eslint ?

**Comment by cedricpinson** [comment]
needs a rebase

**Pull request merged**
