### PR TITLE
Removes deprecated promise API

### PR DESCRIPTION
**Pull request by jtorresfabra**

### CODE REVIEW

**Comment by cedricpinson** [comment]
Did you check performance with those changes ?

**Comment by jtorresfabra** [comment]
Yes I did, but better to test in other devices.

**Comment by jtorresfabra** [comment]
For me it was the same performance.

**Comment by cedricpinson** [comment]
The PR fails the tests actually see 
https://travis-ci.org/cedricpinson/osgjs/builds/255721797#L3213
I think there is an issue with the PR that ensured unittest fails if no test ran

**Comment by jtorresfabra** [comment]
That's good. It means the PR I did about make the node process fail when a test fail is working. There was indeed a test fail and a subtle bug that is now fixed. ready for review now!

**Comment by jtorresfabra** [comment]
Need to add some performance tests to make sure we don't loose a ms :)

**Comment by cedricpinson** [comment]
@jtorresfabra ping, what's the status ?

**Pull request merged**
