### PR TITLE
Fix bbox

### PR DESCRIPTION
**Pull request by stephomi**

### CODE REVIEW

**Comment by stephomi** [comment]
@jtorresfabra you might want to take a look (change in getHomeBound function)

**Comment by jtorresfabra** [comment]
@stephomi  will do, I'll checkout with the CADManipulator.

**Comment by jtorresfabra** [comment]
@stephomi not sure about "flag" name parameter, is a little bit misleading. We could probably find out a better name for the enum and use it in the function call as the name of the parameter (like boundingType or whatever). What do you think?

**Comment by stephomi** [comment]
ok for boundType

**Comment by stephomi** [comment]
In any case getHomeBound returns a boundingSphere 
so, I went for boundStrategy  :).

**Comment by jtorresfabra** [comment]
:+1: Much better.

**Comment by jtorresfabra** [comment]
Also boundPolicy could work, but for me is enough :)

**Comment by cedricpinson** [comment]
let's go for boundType

**Comment by cedricpinson** [comment]
boundStrategy is ok for me

**Pull request merged**
