### PR TITLE
Enhance performance sample

### PR DESCRIPTION
**Pull request by Kuranes**
Adds gui and option to be able to test more performances related renderings

Mesh related:
- deepnees of tree
- number of item of branches
- use different geom at each item or only one item ("instancing")

Stateset/Texture
- with or without texture (which makes it stateset -less)
- number of texture
- texture size

### CODE REVIEW

**Comment by jtorresfabra** [comment]
@Kuranes Is it possible that you want to merge against master and not develop?

**Comment by Kuranes** [comment]
( unclear to me is the new workflow. will ask )

**Comment by cedricpinson** [comment]
Workflow is the same just master is the main branch now 

Cedric

**Comment by cedricpinson** [comment]
I am closing it to avoid confusion. should be rebased on master

**Pull request closed without merging**
