### PR TITLE
Reduces the number of useless default gl calls

### PR DESCRIPTION
**Pull request by stephomi**

### CODE REVIEW

**Comment by jtorresfabra** [comment]
Hi @stephomi,
It doesn't work for me for multipleviewers example. Just talked about that yesterday with @Kuranes.

**Comment by Kuranes** [comment]
- Doesn't work on linux box: mutliple viewer Example, the model on the right has black texture, and sometimes doesn't draw the model

=> perhaps the applyTextureAttributeMaps() has to be done too in the state::applyDefault() to clean some osgjs state info

**Comment by jtorresfabra** [comment]
Adding  this.applyTextureAttributeMapList( this.textureAttributeMapList ); just fixes the issue.

**Comment by stephomi** [comment]
adding back the texture apply

**Pull request merged**
