### PR TITLE
Updates Hammer

### PR DESCRIPTION
**Pull request by Kuranes**
- Fixes bugs on IE11

### CODE REVIEW

**Comment by jtorresfabra** [comment]
Hi @Kuranes,
I updated Hammer time ago to 2.0.3 but I did need to change the osgjs Hammer code because the API changed:

https://github.com/cedricpinson/osgjs/pull/144/

Is the new Hammer version supporting deprecated methods? Or did I miss something?

**Comment by Kuranes** [comment]
I just built myself latest hammer and put it in replacement, without any change, and it worked out of the box. 
It fixed IE11 mouse that wasn't working right anymore And worked everywhere I tested it. 
(win chrome/firefox/ie11 and android chrome/firefox)

**Comment by jtorresfabra** [comment]
It does not work for me in my android tablet. Did you check to remove the hammer.js copy in examples/vendors to be sure that you are using the correct one?

**Comment by Kuranes** [comment]
Yeah, saw that just after the post, some example were hard-linking hammer.1.0.5 instead of 2.0.3
Looking into it.

**Comment by jtorresfabra** [comment]
Check my PR, as it uses the new API, maybe it could be improved but it works for me and my clients so far.

Thanks.

**Comment by jtorresfabra** [comment]
Probably it fixed the IE bugs simply because hammer was not detected... If hammer is detected the IE events go through Hammer library. As far as I investigated time ago.

**Comment by Kuranes** [comment]
Used your PR change to update mine, thanks :)

Works now on android with latest, verified.

(in IE11 Hammer was detected, but torn between touch and mouse and doing touch-like only on desktop)

**Comment by jtorresfabra** [comment]
I believe I had problems with laptops with touch devices using IE11. Maybe is a non usual configuration, but it was a must for my clients. That's the reason why I did https://github.com/cedricpinson/osgjs/blob/8248347747156c71696bd9eae78fec3e727b532e/sources/osgViewer/Viewer.js#L192

**Comment by Kuranes** [comment]
My guess would be that now that it's working on IE11 non touch with vanilla Hammer.js no need to change to support touch, they seems to have sorted that bug.

**Comment by jtorresfabra** [comment]
@Kuranes I checked in a desktop computer of a colleague and the changes are not working ok in IE11 as they are now. Check camera example specially the drag event, do first a couple of movements.

**Comment by Kuranes** [comment]
Added your change to disable ie11 touch

**Comment by jtorresfabra** [comment]
Finally.... :)
Ok, It is good the tests are passing now, I had a problem with phantom browser.

**Comment by jtorresfabra** [comment]
Hey @kuranes,

I want to ask you a favor, for next PR's try to merge my commits, because I justify (in part) my work to my customers with the github log which is an excelent tool for this :)...

Thank you in advance.

**Comment by Kuranes** [comment]
sorry, not yet good enough with git/magit to be able to cherry-pick hunk from other branch.
Will do extra step next time

**Comment by jtorresfabra** [comment]
It's not a big deal, only if it does not hurt you ;), thanks anyway.

2015-03-03 14:44 GMT+01:00 Tuan Kuranes <notifications@github.com>:

> sorry, not yet good enough with git/magit to be able to cherry-pick hunk
> from other branch.
> Will do extra step next time
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cedricpinson/osgjs/pull/265#issuecomment-76947000>.
>



-- 
Jordi Torres

**Pull request merged**
