### PR TITLE
Fix for typos

### PR DESCRIPTION
**Pull request by jtorresfabra**

### CODE REVIEW

**Comment by cedricpinson** [comment]
is it to be sync with osg convention right ? if yes could you keep the old accessors but displaying a deprecated message. I will remove old setEnable a bit later

**Comment by jtorresfabra** [comment]
Ok, also I will change the setEnableFrustumCulling to setFrustumCullingEnabled, that seems the way it is done throughout the OSG code.

**Comment by cedricpinson** [comment]
please add fallback temporary that display a warning message, 'deprecated' ...

**Comment by jtorresfabra** [comment]
Ok, will do asap

**Pull request merged**
