### PR TITLE
Fix for wrong lighting when using textures

### PR DESCRIPTION
**Pull request by jtorresfabra**
According to RedBook computed color in lighting should be 

finalColor = primaryColor ( all lighting stuff using materials) * textureColor + secondaryColor.

That long standing bug made the textured objects appear more lighted than they should.
Easy to see if using texture + material with ambient component + ambient light.

### CODE REVIEW

**Comment by jtorresfabra** [comment]
I also reordered the code to make more sense when reading it. Maybe @Kuranes and @stephomi could take a look also.

**Comment by Kuranes** [comment]
From what I understand, before was
```js
if (textureDiffuse) diffuse = materialDiffuse*textureDiffuse
else diffuse = materialDiffuse
if (vertexDiffuse) diffuse = diffuse *vertexDiffuse

finalColor = lighting(diffuse)

```
after PR it is
```js
if (vertexDiffuse) diffuse = materialDiffuse*vertexDiffuse
else diffuse = materialDiffuse

finalColor = lighting(diffuse)

if (textureDiffuse) finalColor = finalColor * textureDiffuse 
```

meaning texture diffuse color is not a diffuse texture (scaled by light equation NdotL) but more like an Ambient occlusion (light independant) ?

( for me a secondary color is a second vertex color or a second texture color ? )

Maybe there is a possiblity to do "secondary color", but only if we have a vertex color and a texture color, we could check /consider the texture color a secondary (or the vertex color as the secondary) but that's not what current code does ?
(as it always interpret texture color as a secondary, even if there is no primary ?)

**Comment by Kuranes** [comment]
about reordering, perhaps we could move the whole 'alpha' part prior to lighting ?
would make sense to premult before the NDotL as it scale diffuse... may need to read on that.

(at least the alpha, but not premult, as in case of 'discard' and 'mulitple light', it would save a lot of perf)

**Comment by jtorresfabra** [comment]
@Kuranes thanks for the review.

The point of the PR is not the secondary color, as you say it should come with an alternate vertex color. 
The point is the texture should not be affected by lighting. 

> meaning texture diffuse color is not a diffuse texture (scaled by light equation NdotL) but more like an Ambient occlusion (light independant) ?

That's the point, it is like that in OpenGL. Texture Color is combined with primary color ( being primary color materials + color + ligthing ). I can search some links, but it is in the RedBook.

**Comment by jtorresfabra** [comment]
Maybe that shed some light: OpenGL  https://books.google.es/books?id=ckpNmNlLE_sC&pg=PA168&lpg=PA168&dq=fragment+lighting+texture+secondary&source=bl&ots=KGM9tDb0Lx&sig=qiDROsq8Hv8vhG_623bsqhmsIac&hl=es&sa=X&ved=0ahUKEwjXi4PF04jMAhWC2RoKHQcVD8UQ6AEIHzAA#v=onepage&q=fragment%20lighting%20texture%20secondary&f=false

OpenGL computes lighting before TextureMapping, in its default mode.

**Comment by Kuranes** [comment]
Thanks for the reference, much clearer. 
Seems indeed to be Opengl 1.4 behaviour !

**Comment by jtorresfabra** [comment]
Yep, also the seconday is used to apply specular colo, because it could cause some problems. ( See redbook page 450: Secondary Specular Color when lighting is enabled )

**Comment by Kuranes** [comment]
Do you happen to have more on the lighting part,  to be sure to get opengl canonic lighting equation ?
( to double check the createLightiing shader code, particularly light ambient )

**Comment by jtorresfabra** [comment]
That's all I have at the moment, with this PR I just see my scenes as in OSG. But I also noticed that all the ambient variables are not used in the shader functions, so maybe them should be removed from the function parameters. ( materialAmbient and lightAmbient not used at all in https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShader/node/lights.gls)

**Comment by jtorresfabra** [comment]
One more thing, I recall now., by not using materialAmbient and lightAmbient in the lighting functions then it seems attenuation does not affect ambient stuff which maybe wrong. But I don't have a PR for this.

**Comment by Kuranes** [comment]
Thanks for the infos!

**Comment by cedricpinson** [comment]
good for me, could you rebase on develop plz ?

**Comment by jtorresfabra** [comment]
Done.

**Pull request merged**
