### PR TITLE
Added option to set DatabasePath manually for PagedLOD structures

### PR DESCRIPTION
**Pull request by jtorresfabra**

### CODE REVIEW

**Comment by jtorresfabra** [comment]
It's weird as the test failed because:

Warning: The following files are not beautified:
sources/osgViewer/View.js
 
And that file is not modified in the PR

**Comment by jtorresfabra** [comment]
I just updated the PR to develop, it should be enough.

**Comment by jtorresfabra** [comment]
I can't understand what is failing, I'm closing this PR and resending it.

**Comment by cedricpinson** [comment]
Ok it's normal because I merged something that check the coding style about indent ... if you need to fix you can use grunt beautify it will format the code as it should.
There are also tools for sublime/emacs/... that can do it inline while coding

**Pull request closed without merging**
